overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.24.5

allowBuilds:
  prisma: true
  '@prisma/engines': true
  '@prisma/client': true
  esbuild: true
  protobufjs: true
  ssh2: false
  cpu-features: false

minimumReleaseAgeExclude:
  - graphql-yoga@5.24.4
